// lib/constants.ts
export const PREMIUM_PRICE = 11900;
export const PREMIUM_PLAN_NAME = "SQLNova Premium - Acceso de por vida";

export const SQL_BUTTONS = [
  { label: 'SELECT', snippet: 'SELECT ', color: '#93c5fd' },
  { label: 'FROM', snippet: 'FROM ', color: '#93c5fd' },
  { label: 'WHERE', snippet: 'WHERE ', color: '#93c5fd' },
  { label: 'AND', snippet: 'AND ', color: '#93c5fd' },
  { label: 'OR', snippet: 'OR ', color: '#93c5fd' },
  { label: 'JOIN', snippet: 'JOIN ', color: '#a78bfa' },
  { label: 'LEFT JOIN', snippet: 'LEFT JOIN ', color: '#a78bfa' },
  { label: 'INNER JOIN', snippet: 'INNER JOIN ', color: '#a78bfa' },
  { label: 'ON', snippet: 'ON ', color: '#a78bfa' },
  { label: 'GROUP BY', snippet: 'GROUP BY ', color: '#6ee7b7' },
  { label: 'ORDER BY', snippet: 'ORDER BY ', color: '#6ee7b7' },
  { label: 'HAVING', snippet: 'HAVING ', color: '#6ee7b7' },
  { label: 'LIMIT', snippet: 'LIMIT ', color: '#6ee7b7' },
  { label: 'AS', snippet: 'AS ', color: '#fcd34d' },
  { label: 'DISTINCT', snippet: 'DISTINCT ', color: '#fcd34d' },
  { label: 'COUNT(*)', snippet: 'COUNT(*)', color: '#f9a8d4' },
  { label: 'SUM()', snippet: 'SUM()', color: '#f9a8d4' },
  { label: 'AVG()', snippet: 'AVG()', color: '#f9a8d4' },
  { label: 'MAX()', snippet: 'MAX()', color: '#f9a8d4' },
  { label: 'MIN()', snippet: 'MIN()', color: '#f9a8d4' },
  { label: 'IS NULL', snippet: ' IS NULL', color: '#94a3b8' },
  { label: 'IS NOT NULL', snippet: ' IS NOT NULL', color: '#94a3b8' },
  { label: 'IN ()', snippet: ' IN ()', color: '#94a3b8' },
  { label: 'NOT IN ()', snippet: ' NOT IN ()', color: '#94a3b8' },
  { label: 'BETWEEN', snippet: ' BETWEEN ', color: '#94a3b8' },
  { label: 'LIKE', snippet: ' LIKE ', color: '#94a3b8' },
  { label: 'CASE', snippet: 'CASE WHEN  THEN  ELSE  END', color: '#fb923c' },
  { label: 'WITH', snippet: 'WITH  AS (\n  \n)\n', color: '#fb923c' },
  { label: 'OVER()', snippet: ' OVER()', color: '#fb923c' },
  { label: 'PARTITION BY', snippet: 'PARTITION BY ', color: '#fb923c' },
  { label: 'ROW_NUMBER()', snippet: 'ROW_NUMBER()', color: '#fb923c' },
  { label: '*', snippet: '*', color: '#64748b' },
  { label: ',', snippet: ', ', color: '#64748b' },
  { label: '=', snippet: ' = ', color: '#64748b' },
  { label: '!=', snippet: ' != ', color: '#64748b' },
  { label: '>', snippet: ' > ', color: '#64748b' },
  { label: '<', snippet: ' < ', color: '#64748b' },
  { label: '\n', snippet: '\n', color: '#64748b' },
] as const
